[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
gas_reports = [
    "ClarityMarkets",
    "ClarityERC20Factory",
    "ClarityWrappedLong",
    "ClarityWrappedShort"
]
optimizer = true
optimizer_runs = 1000
solc = "0.8.23"

[profile.lite]
optimizer = false

[fuzz]
runs = 1000
max_test_rejects = 1_000_000

[invariant]
runs = 10
depth = 100
max_test_rejects = 1_000_000
call_override = false
fail_on_revert = false

[fmt]
bracket_spacing = false
ignore = ["src/interface/option/IOptionViews.sol", "src/interface/option/IOptionActions.sol"]
int_types = "long"
line_length = 90
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "preserve"
tab_width = 4
wrap_comments = false

[doc]
ignore = ["**/*.t.sol"]
out = "docs"
repository = "https://github.com/neodaoist/clarity"

[etherscan]
# ethereum = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# arbitrum = { key = "${API_KEY_ARBISCAN}" }
# arbitrum_goerli = { key = "${API_KEY_ARBISCAN}" }
# optimism = { key = "${OPTISCAN_API_KEY}" }
# optimism_goerli = { key = "${OPTISCAN_API_KEY}" }
# base = { key = "${BASESCAN_API_KEY}" }
# base_goerli = { key = "${BASESCAN_API_KEY}" }
# polygon = { key = "${POLYGONSCAN_API_KEY}" }
# polygon_mumbai = { key = "${POLYGONSCAN_API_KEY}" }

[rpc_endpoints]
localhost = "http://localhost:8545"
mainnet = "https://mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
sepolia = "https://sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
arbitrum = "https://arbitrum-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
arbitrum_goerli = "https://arbitrum-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
optimism = "https://optimism-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
optimism_goerli = "https://optimism-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
base = "https://base-mainnet.g.alchemy.com/v2/{API_KEY_ALCHEMY}"
base_goerli = "https://base-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/{API_KEY_ALCHEMY}"
polygon_mumbai = "https://polygon-mumbai.g.alchemy.com/v2/{API_KEY_ALCHEMY}"
